Repository SmashGrade/SmashGrade-App, pull requests merged in 2023-10, with the labels that each got.

#23 #7 theme implementieren
  .idea/SmashGrade.iml
  package.json
  src/colors.module.scss
  src/components/SelectWithTitle.module.scss
  src/components/SelectWithTitle.tsx
  src/features/overview/Onboarding.tsx
  src/global.scss
  src/main.tsx
Labels: design

#28 #8 Add I18N
  README.md
  package-lock.json
  package.json
  src/components/LocaleSwitcher.tsx
  src/features/overview/Onboarding.tsx
  src/i18n/Locale.ts
  src/i18n/ReactIntlProvider.tsx
  src/i18n/compiled-lang/de.json
  src/i18n/compiled-lang/en.json
  src/i18n/compiled-lang/fr.json
  src/i18n/custom-react-intl.d.ts
  src/i18n/lang/de.json
  src/i18n/lang/en.json
  src/i18n/lang/fr.json
  src/main.tsx
  tsconfig.json
Labels: feature

#31 Added configuration to run with JSON Server in App Service
  .env.development
  .env.production
  .eslintrc.cjs
  .github/workflows/azure-static-web-apps-salmon-meadow-0f230d803.yml
  .github/workflows/dev_wapp-smashgrade.yml
  .prettierignore
  README.md
  api/package.json
  api/server.ts
  db.json
  package-lock.json
  package.json
  src/colors.module.scss
  src/components/SelectWithTitle.module.scss
  src/features/overview/Onboarding.tsx
  src/global.scss
  src/i18n/compiled-lang/de.json
  src/i18n/compiled-lang/en.json
  src/i18n/compiled-lang/fr.json
  src/i18n/lang/de.json
  src/i18n/lang/en.json
  src/i18n/lang/fr.json
  src/main.tsx
  tsconfig.json
  tsconfig.node.json
Labels: configuration

#36 #32 deploy pr to azure slot
  .github/workflows/azure-static-web-apps-salmon-meadow-0f230d803.yml
  .github/workflows/deploy-to-azure-app-service.yml
  .github/workflows/dev_wapp-smashgrade.yml
  api/package-lock.json
  api/package.json
  api/server.ts
  favicon-16x16.png
  favicon-32x32.png
  favicon.ico
  index.html
  package-lock.json
  package.json
  site.webmanifest
  tsconfig.json
Labels: configuration

#67 #40 header navigation
  .env.development
  .github/workflows/deploy-to-azure-app-service.yml
  .husky/pre-commit
  package.json
  src/App.tsx
  src/assets/images/nav_logo_250.png
  src/assets/images/smashgrade_logo_transparent.png
  src/components/Navigation.module.scss
  src/components/Navigation.tsx
  src/i18n/compiled-lang/de.json
  src/i18n/compiled-lang/en.json
  src/i18n/compiled-lang/fr.json
  src/i18n/lang/de.json
  src/i18n/lang/en.json
  src/i18n/lang/fr.json
  src/main.tsx
  src/pages/PlaceholderCurriculumPage.tsx
Labels: feature

#68 #60: Added AG Grid and sample course grid
  db.json
  package-lock.json
  package.json
  src/components/Grid.tsx
  src/components/Navigation.tsx
  src/features/course/Course.module.scss
  src/features/course/Course.tsx
  src/main.tsx
  src/pages/CoursePage.tsx
  src/pages/OnboardingPage.tsx
Labels: feature
